name: Simulation batch

# permet de le déclencher manuellement depuis l’UI
on:
  workflow_dispatch:

jobs:
  run-sim:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
    # 1) récupère votre code
    - uses: actions/checkout@v3

    # 2) installe le SDK .NET
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'  # ou 6.0.x selon votre projet

    # 3) compile et lance votre simulateur
    - name: Run simulation
      run: |
        dotnet build
        dotnet run -- tuneDescent watterbattle-sim.csproj > simulation-output.txt

    # 4) expose le fichier de sortie pour téléchargement
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: simulation-output
        path: simulation-output.txt
